export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_SIDEBAR_COMPONENT = "SET_SIDEBAR_COMPONENT";

export const SET_ITEM_DETAILS = "SET_ITEM_DETAILS";
export const ADD_TO_LIST = "ADD_TO_LIST";
