export const data = {
  categories: ["Fruit and Vegetables", "Meat and Fish"],
  items: [
    {
      id: 1,
      category: "Fruit and Vegetables",
      name: "avocado",
      note: "Nutrient-dense foods are those that provide substantial amounts of vitamins, minerals and other nutrients with relatively few calories. One-third of a medium avocado (50 g) has 80 calories and contributes nearly 20 vitamins and minerals, making it a great nutrient-dense food choice. ",
      image:
        "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=968&q=80",
    },
    {
      id: 2,
      category: "Fruit and Vegetables",
      name: "banana",
      note: "banana desc",
      image: null,
    },
    {
      id: 3,
      category: "Fruit and Vegetables",
      name: "bunch of carrots 5pcs",
      note: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a ligula lobortis, interdum mi nec, ornare mi. Phasellus molestie elit sed porta finibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In a leo porttitor, dictum justo sit amet, ullamcorper lorem. Fusce placerat nisi a felis eleifend semper. Proin lacinia tellus eu lectus sagittis scelerisque. Maecenas neque velit, molestie id pulvinar interdum, tristique vel est. Aenean accumsan, lacus in molestie convallis, justo erat pellentesque leo, ac sagittis risus nulla vitae massa. Pellentesque id felis in lacus dignissim mollis id commodo turpis. In vel vulputate ipsum, quis facilisis orci. Vestibulum posuere enim arcu, et dapibus nunc elementum in. Sed et mi posuere purus cursus convallis eu in ex. Etiam vestibulum lorem aliquam massa varius, vel sagittis dui lacinia. Maecenas dictum quis ex ac aliquet. Duis tristique neque sit amet velit rutrum, non accumsan elit lacinia.",
      image: null,
    },
    {
      id: 4,
      category: "Fruit and Vegetables",
      name: "chicken 1kg",
      note: "chicken desc",
      image: null,
    },
    {
      id: 5,
      category: "Fruit and Vegetables",
      name: "pre-cooked corn 450g",
      note: "corn desc",
      image: null,
    },
    {
      id: 6,
      category: "Fruit and Vegetables",
      name: "mandarin nadorcott",
      note: "mandarin desc",
      image: null,
    },
    {
      id: 7,
      category: "Fruit and Vegetables",
      name: "piele de sapo melon",
      note: "melon desc",
      image: null,
    },
    {
      id: 8,
      category: "Fruit and Vegetables",
      name: "watermelon",
      note: "watermelon desc",
      image: null,
    },
    {
      id: 9,
      category: "Meat and Fish",
      name: "chicken leg box",
      note: "chicken desc",
      image: null,
    },
    {
      id: 10,
      category: "Meat and Fish",
      name: "chicken 1kg",
      note: "chicken desc",
      image: null,
    },
    {
      id: 11,
      category: "Meat and Fish",
      name: "pork fillets 450g",
      note: "pork desc",
      image: null,
    },
    {
      id: 12,
      category: "Meat and Fish",
      name: "salmon 1kg",
      note: "salmon desc",
      image: null,
    },
  ],
};
